### ISSUE TITLE
使用-config config.json运行的时候host不生效

### ISSUE THREAD

**Issue by smileawei** [childe/ldap-nginx-golang#1]
使用最新的编译好的二进制文件。更改config.json里的host选项为0.0.0.0后。运行程序还是显示监听127.0.0.1

**Comment by childe** [comment]
哇嘿嘿,  对不起, 我看了一下代码, Host port只能在程序参数里面指定... :(

**Comment by smileawei** [comment]
嗯嗯 已经搞定了多谢🙏。感谢，很好用 比nginx官方的方案好用
